#!/bin/bash

print_exit() {
  mes=$1
  code=$2
  detail=$3

  echo "=== プッシュに失敗しました ==="
  echo "$mes"
  echo "$detail"
  exit $code
}

change_files=$(git status --short)
if [ -n "$change_files" ]; then
  print_exit "コミットされていない差分があります。" 2 "$change_files"
fi

npm run lint
if [ $? != 0 ]; then
  print_exit "Lintに失敗しました。" 3
fi

npm run headless-test
if [ $? != 0 ]; then
  print_exit "テストに失敗しました。" 4
fi

npm run fix
change_files=$(git status --short)
if [ -n "$change_files" ]; then
  print_exit "オートフォーマットで差分が出ています。" 6 "$change_files"
fi
