import { PromptObject } from 'prompts';
import validateNpmPackageName from 'validate-npm-package-name';
import { ProjectTypes, ProjectOptionDef } from '../ProjectOptions';

/**
 * project types choice
 */
export const ProjectTypesChoices = [...ProjectTypes].map((type) => {
  return {
    title: type,
    value: type,
  };
});

/**
 * Generator dialog input options
 */
export const DialogInputOptions: PromptObject<string>[] = [
  {
    type: 'autocomplete',
    name: 'type',
    message: ProjectOptionDef.description.type,
    initial: ProjectOptionDef.default.type,
    choices: ProjectTypesChoices,
  },
  {
    type: 'text',
    name: 'projectName',
    message: ProjectOptionDef.description.projectName,
    initial: ProjectOptionDef.default.projectName,
    validate: (value: string) => {
      const ctx = validateNpmPackageName(value);
      if (ctx.validForNewPackages) {
        return true;
      } else {
        const getItems = (arr: string[] | undefined) => {
          if (arr === undefined) {
            return new Array<string>();
          } else {
            return arr;
          }
        };

        return getItems(ctx.errors)
          .concat(getItems(ctx.warnings))
          .join(' and ');
      }
    },
  },
  {
    type: 'text',
    name: 'description',
    message: ProjectOptionDef.description.description,
    initial: ProjectOptionDef.default.description,
  },
  {
    type: 'text',
    name: 'author',
    message: ProjectOptionDef.description.author,
    initial: ProjectOptionDef.default.author,
  },
  {
    type: 'autocomplete',
    name: 'license',
    message: ProjectOptionDef.description.license,
    initial: ProjectOptionDef.default.license,
    choices: [
      { title: '0BSD', value: '0BSD' },
      { title: 'AAL', value: 'AAL' },
      { title: 'Abstyles', value: 'Abstyles' },
      { title: 'Adobe-2006', value: 'Adobe-2006' },
      { title: 'Adobe-Glyph', value: 'Adobe-Glyph' },
      { title: 'ADSL', value: 'ADSL' },
      { title: 'AFL-1.1', value: 'AFL-1.1' },
      { title: 'AFL-1.2', value: 'AFL-1.2' },
      { title: 'AFL-2.0', value: 'AFL-2.0' },
      { title: 'AFL-2.1', value: 'AFL-2.1' },
      { title: 'AFL-3.0', value: 'AFL-3.0' },
      { title: 'Afmparse', value: 'Afmparse' },
      { title: 'AGPL-1.0-only', value: 'AGPL-1.0-only' },
      { title: 'AGPL-1.0-or-later', value: 'AGPL-1.0-or-later' },
      { title: 'AGPL-3.0-only', value: 'AGPL-3.0-only' },
      { title: 'AGPL-3.0-or-later', value: 'AGPL-3.0-or-later' },
      { title: 'Aladdin', value: 'Aladdin' },
      { title: 'AMDPLPA', value: 'AMDPLPA' },
      { title: 'AML', value: 'AML' },
      { title: 'AMPAS', value: 'AMPAS' },
      { title: 'ANTLR-PD', value: 'ANTLR-PD' },
      { title: 'Apache-1.0', value: 'Apache-1.0' },
      { title: 'Apache-1.1', value: 'Apache-1.1' },
      { title: 'Apache-2.0', value: 'Apache-2.0' },
      { title: 'APAFML', value: 'APAFML' },
      { title: 'APL-1.0', value: 'APL-1.0' },
      { title: 'APSL-1.0', value: 'APSL-1.0' },
      { title: 'APSL-1.1', value: 'APSL-1.1' },
      { title: 'APSL-1.2', value: 'APSL-1.2' },
      { title: 'APSL-2.0', value: 'APSL-2.0' },
      { title: 'Artistic-1.0', value: 'Artistic-1.0' },
      { title: 'Artistic-1.0-cl8', value: 'Artistic-1.0-cl8' },
      { title: 'Artistic-1.0-Perl', value: 'Artistic-1.0-Perl' },
      { title: 'Artistic-2.0', value: 'Artistic-2.0' },
      { title: 'Bahyph', value: 'Bahyph' },
      { title: 'Barr', value: 'Barr' },
      { title: 'Beerware', value: 'Beerware' },
      { title: 'BitTorrent-1.0', value: 'BitTorrent-1.0' },
      { title: 'BitTorrent-1.1', value: 'BitTorrent-1.1' },
      { title: 'blessing', value: 'blessing' },
      { title: 'BlueOak-1.0.0', value: 'BlueOak-1.0.0' },
      { title: 'Borceux', value: 'Borceux' },
      { title: 'BSD-1-Clause', value: 'BSD-1-Clause' },
      { title: 'BSD-2-Clause', value: 'BSD-2-Clause' },
      { title: 'BSD-2-Clause-Patent', value: 'BSD-2-Clause-Patent' },
      { title: 'BSD-2-Clause-Views', value: 'BSD-2-Clause-Views' },
      { title: 'BSD-3-Clause', value: 'BSD-3-Clause' },
      { title: 'BSD-3-Clause-Attribution', value: 'BSD-3-Clause-Attribution' },
      { title: 'BSD-3-Clause-Clear', value: 'BSD-3-Clause-Clear' },
      { title: 'BSD-3-Clause-LBNL', value: 'BSD-3-Clause-LBNL' },
      {
        title: 'BSD-3-Clause-No-Nuclear-License',
        value: 'BSD-3-Clause-No-Nuclear-License',
      },
      {
        title: 'BSD-3-Clause-No-Nuclear-License-2014',
        value: 'BSD-3-Clause-No-Nuclear-License-2014',
      },
      {
        title: 'BSD-3-Clause-No-Nuclear-Warranty',
        value: 'BSD-3-Clause-No-Nuclear-Warranty',
      },
      { title: 'BSD-3-Clause-Open-MPI', value: 'BSD-3-Clause-Open-MPI' },
      { title: 'BSD-4-Clause', value: 'BSD-4-Clause' },
      { title: 'BSD-4-Clause-UC', value: 'BSD-4-Clause-UC' },
      { title: 'BSD-Protection', value: 'BSD-Protection' },
      { title: 'BSD-Source-Code', value: 'BSD-Source-Code' },
      { title: 'BSL-1.0', value: 'BSL-1.0' },
      { title: 'bzip2-1.0.5', value: 'bzip2-1.0.5' },
      { title: 'bzip2-1.0.6', value: 'bzip2-1.0.6' },
      { title: 'CAL-1.0', value: 'CAL-1.0' },
      {
        title: 'CAL-1.0-Combined-Work-Exception',
        value: 'CAL-1.0-Combined-Work-Exception',
      },
      { title: 'Caldera', value: 'Caldera' },
      { title: 'CATOSL-1.1', value: 'CATOSL-1.1' },
      { title: 'CC-BY-1.0', value: 'CC-BY-1.0' },
      { title: 'CC-BY-2.0', value: 'CC-BY-2.0' },
      { title: 'CC-BY-2.5', value: 'CC-BY-2.5' },
      { title: 'CC-BY-3.0', value: 'CC-BY-3.0' },
      { title: 'CC-BY-3.0-AT', value: 'CC-BY-3.0-AT' },
      { title: 'CC-BY-4.0', value: 'CC-BY-4.0' },
      { title: 'CC-BY-NC-1.0', value: 'CC-BY-NC-1.0' },
      { title: 'CC-BY-NC-2.0', value: 'CC-BY-NC-2.0' },
      { title: 'CC-BY-NC-2.5', value: 'CC-BY-NC-2.5' },
      { title: 'CC-BY-NC-3.0', value: 'CC-BY-NC-3.0' },
      { title: 'CC-BY-NC-4.0', value: 'CC-BY-NC-4.0' },
      { title: 'CC-BY-NC-ND-1.0', value: 'CC-BY-NC-ND-1.0' },
      { title: 'CC-BY-NC-ND-2.0', value: 'CC-BY-NC-ND-2.0' },
      { title: 'CC-BY-NC-ND-2.5', value: 'CC-BY-NC-ND-2.5' },
      { title: 'CC-BY-NC-ND-3.0', value: 'CC-BY-NC-ND-3.0' },
      { title: 'CC-BY-NC-ND-3.0-IGO', value: 'CC-BY-NC-ND-3.0-IGO' },
      { title: 'CC-BY-NC-ND-4.0', value: 'CC-BY-NC-ND-4.0' },
      { title: 'CC-BY-NC-SA-1.0', value: 'CC-BY-NC-SA-1.0' },
      { title: 'CC-BY-NC-SA-2.0', value: 'CC-BY-NC-SA-2.0' },
      { title: 'CC-BY-NC-SA-2.5', value: 'CC-BY-NC-SA-2.5' },
      { title: 'CC-BY-NC-SA-3.0', value: 'CC-BY-NC-SA-3.0' },
      { title: 'CC-BY-NC-SA-4.0', value: 'CC-BY-NC-SA-4.0' },
      { title: 'CC-BY-ND-1.0', value: 'CC-BY-ND-1.0' },
      { title: 'CC-BY-ND-2.0', value: 'CC-BY-ND-2.0' },
      { title: 'CC-BY-ND-2.5', value: 'CC-BY-ND-2.5' },
      { title: 'CC-BY-ND-3.0', value: 'CC-BY-ND-3.0' },
      { title: 'CC-BY-ND-4.0', value: 'CC-BY-ND-4.0' },
      { title: 'CC-BY-SA-1.0', value: 'CC-BY-SA-1.0' },
      { title: 'CC-BY-SA-2.0', value: 'CC-BY-SA-2.0' },
      { title: 'CC-BY-SA-2.5', value: 'CC-BY-SA-2.5' },
      { title: 'CC-BY-SA-3.0', value: 'CC-BY-SA-3.0' },
      { title: 'CC-BY-SA-3.0-AT', value: 'CC-BY-SA-3.0-AT' },
      { title: 'CC-BY-SA-4.0', value: 'CC-BY-SA-4.0' },
      { title: 'CC-PDDC', value: 'CC-PDDC' },
      { title: 'CC0-1.0', value: 'CC0-1.0' },
      { title: 'CDDL-1.0', value: 'CDDL-1.0' },
      { title: 'CDDL-1.1', value: 'CDDL-1.1' },
      { title: 'CDLA-Permissive-1.0', value: 'CDLA-Permissive-1.0' },
      { title: 'CDLA-Sharing-1.0', value: 'CDLA-Sharing-1.0' },
      { title: 'CECILL-1.0', value: 'CECILL-1.0' },
      { title: 'CECILL-1.1', value: 'CECILL-1.1' },
      { title: 'CECILL-2.0', value: 'CECILL-2.0' },
      { title: 'CECILL-2.1', value: 'CECILL-2.1' },
      { title: 'CECILL-B', value: 'CECILL-B' },
      { title: 'CECILL-C', value: 'CECILL-C' },
      { title: 'CERN-OHL-1.1', value: 'CERN-OHL-1.1' },
      { title: 'CERN-OHL-1.2', value: 'CERN-OHL-1.2' },
      { title: 'CERN-OHL-P-2.0', value: 'CERN-OHL-P-2.0' },
      { title: 'CERN-OHL-S-2.0', value: 'CERN-OHL-S-2.0' },
      { title: 'CERN-OHL-W-2.0', value: 'CERN-OHL-W-2.0' },
      { title: 'ClArtistic', value: 'ClArtistic' },
      { title: 'CNRI-Jython', value: 'CNRI-Jython' },
      { title: 'CNRI-Python', value: 'CNRI-Python' },
      {
        title: 'CNRI-Python-GPL-Compatible',
        value: 'CNRI-Python-GPL-Compatible',
      },
      { title: 'Condor-1.1', value: 'Condor-1.1' },
      { title: 'copyleft-next-0.3.0', value: 'copyleft-next-0.3.0' },
      { title: 'copyleft-next-0.3.1', value: 'copyleft-next-0.3.1' },
      { title: 'CPAL-1.0', value: 'CPAL-1.0' },
      { title: 'CPL-1.0', value: 'CPL-1.0' },
      { title: 'CPOL-1.02', value: 'CPOL-1.02' },
      { title: 'Crossword', value: 'Crossword' },
      { title: 'CrystalStacker', value: 'CrystalStacker' },
      { title: 'CUA-OPL-1.0', value: 'CUA-OPL-1.0' },
      { title: 'Cube', value: 'Cube' },
      { title: 'curl', value: 'curl' },
      { title: 'D-FSL-1.0', value: 'D-FSL-1.0' },
      { title: 'diffmark', value: 'diffmark' },
      { title: 'DOC', value: 'DOC' },
      { title: 'Dotseqn', value: 'Dotseqn' },
      { title: 'DSDP', value: 'DSDP' },
      { title: 'dvipdfm', value: 'dvipdfm' },
      { title: 'ECL-1.0', value: 'ECL-1.0' },
      { title: 'ECL-2.0', value: 'ECL-2.0' },
      { title: 'EFL-1.0', value: 'EFL-1.0' },
      { title: 'EFL-2.0', value: 'EFL-2.0' },
      { title: 'eGenix', value: 'eGenix' },
      { title: 'Entessa', value: 'Entessa' },
      { title: 'EPICS', value: 'EPICS' },
      { title: 'EPL-1.0', value: 'EPL-1.0' },
      { title: 'EPL-2.0', value: 'EPL-2.0' },
      { title: 'ErlPL-1.1', value: 'ErlPL-1.1' },
      { title: 'etalab-2.0', value: 'etalab-2.0' },
      { title: 'EUDatagrid', value: 'EUDatagrid' },
      { title: 'EUPL-1.0', value: 'EUPL-1.0' },
      { title: 'EUPL-1.1', value: 'EUPL-1.1' },
      { title: 'EUPL-1.2', value: 'EUPL-1.2' },
      { title: 'Eurosym', value: 'Eurosym' },
      { title: 'Fair', value: 'Fair' },
      { title: 'Frameworx-1.0', value: 'Frameworx-1.0' },
      { title: 'FreeImage', value: 'FreeImage' },
      { title: 'FSFAP', value: 'FSFAP' },
      { title: 'FSFUL', value: 'FSFUL' },
      { title: 'FSFULLR', value: 'FSFULLR' },
      { title: 'FTL', value: 'FTL' },
      { title: 'GFDL-1.1-invariants-only', value: 'GFDL-1.1-invariants-only' },
      {
        title: 'GFDL-1.1-invariants-or-later',
        value: 'GFDL-1.1-invariants-or-later',
      },
      {
        title: 'GFDL-1.1-no-invariants-only',
        value: 'GFDL-1.1-no-invariants-only',
      },
      {
        title: 'GFDL-1.1-no-invariants-or-later',
        value: 'GFDL-1.1-no-invariants-or-later',
      },
      { title: 'GFDL-1.1-only', value: 'GFDL-1.1-only' },
      { title: 'GFDL-1.1-or-later', value: 'GFDL-1.1-or-later' },
      { title: 'GFDL-1.2-invariants-only', value: 'GFDL-1.2-invariants-only' },
      {
        title: 'GFDL-1.2-invariants-or-later',
        value: 'GFDL-1.2-invariants-or-later',
      },
      {
        title: 'GFDL-1.2-no-invariants-only',
        value: 'GFDL-1.2-no-invariants-only',
      },
      {
        title: 'GFDL-1.2-no-invariants-or-later',
        value: 'GFDL-1.2-no-invariants-or-later',
      },
      { title: 'GFDL-1.2-only', value: 'GFDL-1.2-only' },
      { title: 'GFDL-1.2-or-later', value: 'GFDL-1.2-or-later' },
      { title: 'GFDL-1.3-invariants-only', value: 'GFDL-1.3-invariants-only' },
      {
        title: 'GFDL-1.3-invariants-or-later',
        value: 'GFDL-1.3-invariants-or-later',
      },
      {
        title: 'GFDL-1.3-no-invariants-only',
        value: 'GFDL-1.3-no-invariants-only',
      },
      {
        title: 'GFDL-1.3-no-invariants-or-later',
        value: 'GFDL-1.3-no-invariants-or-later',
      },
      { title: 'GFDL-1.3-only', value: 'GFDL-1.3-only' },
      { title: 'GFDL-1.3-or-later', value: 'GFDL-1.3-or-later' },
      { title: 'Giftware', value: 'Giftware' },
      { title: 'GL2PS', value: 'GL2PS' },
      { title: 'Glide', value: 'Glide' },
      { title: 'Glulxe', value: 'Glulxe' },
      { title: 'GLWTPL', value: 'GLWTPL' },
      { title: 'gnuplot', value: 'gnuplot' },
      { title: 'GPL-1.0-only', value: 'GPL-1.0-only' },
      { title: 'GPL-1.0-or-later', value: 'GPL-1.0-or-later' },
      { title: 'GPL-2.0-only', value: 'GPL-2.0-only' },
      { title: 'GPL-2.0-or-later', value: 'GPL-2.0-or-later' },
      { title: 'GPL-3.0-only', value: 'GPL-3.0-only' },
      { title: 'GPL-3.0-or-later', value: 'GPL-3.0-or-later' },
      { title: 'gSOAP-1.3b', value: 'gSOAP-1.3b' },
      { title: 'HaskellReport', value: 'HaskellReport' },
      { title: 'Hippocratic-2.1', value: 'Hippocratic-2.1' },
      { title: 'HPND', value: 'HPND' },
      { title: 'HPND-sell-variant', value: 'HPND-sell-variant' },
      { title: 'IBM-pibs', value: 'IBM-pibs' },
      { title: 'ICU', value: 'ICU' },
      { title: 'IJG', value: 'IJG' },
      { title: 'ImageMagick', value: 'ImageMagick' },
      { title: 'iMatix', value: 'iMatix' },
      { title: 'Imlib2', value: 'Imlib2' },
      { title: 'Info-ZIP', value: 'Info-ZIP' },
      { title: 'Intel', value: 'Intel' },
      { title: 'Intel-ACPI', value: 'Intel-ACPI' },
      { title: 'Interbase-1.0', value: 'Interbase-1.0' },
      { title: 'IPA', value: 'IPA' },
      { title: 'IPL-1.0', value: 'IPL-1.0' },
      { title: 'ISC', value: 'ISC' },
      { title: 'JasPer-2.0', value: 'JasPer-2.0' },
      { title: 'JPNIC', value: 'JPNIC' },
      { title: 'JSON', value: 'JSON' },
      { title: 'LAL-1.2', value: 'LAL-1.2' },
      { title: 'LAL-1.3', value: 'LAL-1.3' },
      { title: 'Latex2e', value: 'Latex2e' },
      { title: 'Leptonica', value: 'Leptonica' },
      { title: 'LGPL-2.0-only', value: 'LGPL-2.0-only' },
      { title: 'LGPL-2.0-or-later', value: 'LGPL-2.0-or-later' },
      { title: 'LGPL-2.1-only', value: 'LGPL-2.1-only' },
      { title: 'LGPL-2.1-or-later', value: 'LGPL-2.1-or-later' },
      { title: 'LGPL-3.0-only', value: 'LGPL-3.0-only' },
      { title: 'LGPL-3.0-or-later', value: 'LGPL-3.0-or-later' },
      { title: 'LGPLLR', value: 'LGPLLR' },
      { title: 'Libpng', value: 'Libpng' },
      { title: 'libpng-2.0', value: 'libpng-2.0' },
      { title: 'libselinux-1.0', value: 'libselinux-1.0' },
      { title: 'libtiff', value: 'libtiff' },
      { title: 'LiLiQ-P-1.1', value: 'LiLiQ-P-1.1' },
      { title: 'LiLiQ-R-1.1', value: 'LiLiQ-R-1.1' },
      { title: 'LiLiQ-Rplus-1.1', value: 'LiLiQ-Rplus-1.1' },
      { title: 'Linux-OpenIB', value: 'Linux-OpenIB' },
      { title: 'LPL-1.0', value: 'LPL-1.0' },
      { title: 'LPL-1.02', value: 'LPL-1.02' },
      { title: 'LPPL-1.0', value: 'LPPL-1.0' },
      { title: 'LPPL-1.1', value: 'LPPL-1.1' },
      { title: 'LPPL-1.2', value: 'LPPL-1.2' },
      { title: 'LPPL-1.3a', value: 'LPPL-1.3a' },
      { title: 'LPPL-1.3c', value: 'LPPL-1.3c' },
      { title: 'MakeIndex', value: 'MakeIndex' },
      { title: 'MirOS', value: 'MirOS' },
      { title: 'MIT', value: 'MIT' },
      { title: 'MIT-0', value: 'MIT-0' },
      { title: 'MIT-advertising', value: 'MIT-advertising' },
      { title: 'MIT-CMU', value: 'MIT-CMU' },
      { title: 'MIT-enna', value: 'MIT-enna' },
      { title: 'MIT-feh', value: 'MIT-feh' },
      { title: 'MITNFA', value: 'MITNFA' },
      { title: 'Motosoto', value: 'Motosoto' },
      { title: 'mpich2', value: 'mpich2' },
      { title: 'MPL-1.0', value: 'MPL-1.0' },
      { title: 'MPL-1.1', value: 'MPL-1.1' },
      { title: 'MPL-2.0', value: 'MPL-2.0' },
      {
        title: 'MPL-2.0-no-copyleft-exception',
        value: 'MPL-2.0-no-copyleft-exception',
      },
      { title: 'MS-PL', value: 'MS-PL' },
      { title: 'MS-RL', value: 'MS-RL' },
      { title: 'MTLL', value: 'MTLL' },
      { title: 'MulanPSL-1.0', value: 'MulanPSL-1.0' },
      { title: 'MulanPSL-2.0', value: 'MulanPSL-2.0' },
      { title: 'Multics', value: 'Multics' },
      { title: 'Mup', value: 'Mup' },
      { title: 'NASA-1.3', value: 'NASA-1.3' },
      { title: 'Naumen', value: 'Naumen' },
      { title: 'NBPL-1.0', value: 'NBPL-1.0' },
      { title: 'NCGL-UK-2.0', value: 'NCGL-UK-2.0' },
      { title: 'NCSA', value: 'NCSA' },
      { title: 'Net-SNMP', value: 'Net-SNMP' },
      { title: 'NetCDF', value: 'NetCDF' },
      { title: 'Newsletr', value: 'Newsletr' },
      { title: 'NGPL', value: 'NGPL' },
      { title: 'NIST-PD', value: 'NIST-PD' },
      { title: 'NIST-PD-fallback', value: 'NIST-PD-fallback' },
      { title: 'NLOD-1.0', value: 'NLOD-1.0' },
      { title: 'NLPL', value: 'NLPL' },
      { title: 'Nokia', value: 'Nokia' },
      { title: 'NOSL', value: 'NOSL' },
      { title: 'Noweb', value: 'Noweb' },
      { title: 'NPL-1.0', value: 'NPL-1.0' },
      { title: 'NPL-1.1', value: 'NPL-1.1' },
      { title: 'NPOSL-3.0', value: 'NPOSL-3.0' },
      { title: 'NRL', value: 'NRL' },
      { title: 'NTP', value: 'NTP' },
      { title: 'NTP-0', value: 'NTP-0' },
      { title: 'O-UDA-1.0', value: 'O-UDA-1.0' },
      { title: 'OCCT-PL', value: 'OCCT-PL' },
      { title: 'OCLC-2.0', value: 'OCLC-2.0' },
      { title: 'ODbL-1.0', value: 'ODbL-1.0' },
      { title: 'ODC-By-1.0', value: 'ODC-By-1.0' },
      { title: 'OFL-1.0', value: 'OFL-1.0' },
      { title: 'OFL-1.0-no-RFN', value: 'OFL-1.0-no-RFN' },
      { title: 'OFL-1.0-RFN', value: 'OFL-1.0-RFN' },
      { title: 'OFL-1.1', value: 'OFL-1.1' },
      { title: 'OFL-1.1-no-RFN', value: 'OFL-1.1-no-RFN' },
      { title: 'OFL-1.1-RFN', value: 'OFL-1.1-RFN' },
      { title: 'OGC-1.0', value: 'OGC-1.0' },
      { title: 'OGL-Canada-2.0', value: 'OGL-Canada-2.0' },
      { title: 'OGL-UK-1.0', value: 'OGL-UK-1.0' },
      { title: 'OGL-UK-2.0', value: 'OGL-UK-2.0' },
      { title: 'OGL-UK-3.0', value: 'OGL-UK-3.0' },
      { title: 'OGTSL', value: 'OGTSL' },
      { title: 'OLDAP-1.1', value: 'OLDAP-1.1' },
      { title: 'OLDAP-1.2', value: 'OLDAP-1.2' },
      { title: 'OLDAP-1.3', value: 'OLDAP-1.3' },
      { title: 'OLDAP-1.4', value: 'OLDAP-1.4' },
      { title: 'OLDAP-2.0', value: 'OLDAP-2.0' },
      { title: 'OLDAP-2.0.1', value: 'OLDAP-2.0.1' },
      { title: 'OLDAP-2.1', value: 'OLDAP-2.1' },
      { title: 'OLDAP-2.2', value: 'OLDAP-2.2' },
      { title: 'OLDAP-2.2.1', value: 'OLDAP-2.2.1' },
      { title: 'OLDAP-2.2.2', value: 'OLDAP-2.2.2' },
      { title: 'OLDAP-2.3', value: 'OLDAP-2.3' },
      { title: 'OLDAP-2.4', value: 'OLDAP-2.4' },
      { title: 'OLDAP-2.5', value: 'OLDAP-2.5' },
      { title: 'OLDAP-2.6', value: 'OLDAP-2.6' },
      { title: 'OLDAP-2.7', value: 'OLDAP-2.7' },
      { title: 'OLDAP-2.8', value: 'OLDAP-2.8' },
      { title: 'OML', value: 'OML' },
      { title: 'OpenSSL', value: 'OpenSSL' },
      { title: 'OPL-1.0', value: 'OPL-1.0' },
      { title: 'OSET-PL-2.1', value: 'OSET-PL-2.1' },
      { title: 'OSL-1.0', value: 'OSL-1.0' },
      { title: 'OSL-1.1', value: 'OSL-1.1' },
      { title: 'OSL-2.0', value: 'OSL-2.0' },
      { title: 'OSL-2.1', value: 'OSL-2.1' },
      { title: 'OSL-3.0', value: 'OSL-3.0' },
      { title: 'Parity-6.0.0', value: 'Parity-6.0.0' },
      { title: 'Parity-7.0.0', value: 'Parity-7.0.0' },
      { title: 'PDDL-1.0', value: 'PDDL-1.0' },
      { title: 'PHP-3.0', value: 'PHP-3.0' },
      { title: 'PHP-3.01', value: 'PHP-3.01' },
      { title: 'Plexus', value: 'Plexus' },
      {
        title: 'PolyForm-Noncommercial-1.0.0',
        value: 'PolyForm-Noncommercial-1.0.0',
      },
      {
        title: 'PolyForm-Small-Business-1.0.0',
        value: 'PolyForm-Small-Business-1.0.0',
      },
      { title: 'PostgreSQL', value: 'PostgreSQL' },
      { title: 'PSF-2.0', value: 'PSF-2.0' },
      { title: 'psfrag', value: 'psfrag' },
      { title: 'psutils', value: 'psutils' },
      { title: 'Python-2.0', value: 'Python-2.0' },
      { title: 'Qhull', value: 'Qhull' },
      { title: 'QPL-1.0', value: 'QPL-1.0' },
      { title: 'Rdisc', value: 'Rdisc' },
      { title: 'RHeCos-1.1', value: 'RHeCos-1.1' },
      { title: 'RPL-1.1', value: 'RPL-1.1' },
      { title: 'RPL-1.5', value: 'RPL-1.5' },
      { title: 'RPSL-1.0', value: 'RPSL-1.0' },
      { title: 'RSA-MD', value: 'RSA-MD' },
      { title: 'RSCPL', value: 'RSCPL' },
      { title: 'Ruby', value: 'Ruby' },
      { title: 'SAX-PD', value: 'SAX-PD' },
      { title: 'Saxpath', value: 'Saxpath' },
      { title: 'SCEA', value: 'SCEA' },
      { title: 'Sendmail', value: 'Sendmail' },
      { title: 'Sendmail-8.23', value: 'Sendmail-8.23' },
      { title: 'SGI-B-1.0', value: 'SGI-B-1.0' },
      { title: 'SGI-B-1.1', value: 'SGI-B-1.1' },
      { title: 'SGI-B-2.0', value: 'SGI-B-2.0' },
      { title: 'SHL-0.5', value: 'SHL-0.5' },
      { title: 'SHL-0.51', value: 'SHL-0.51' },
      { title: 'SimPL-2.0', value: 'SimPL-2.0' },
      { title: 'SISSL', value: 'SISSL' },
      { title: 'SISSL-1.2', value: 'SISSL-1.2' },
      { title: 'Sleepycat', value: 'Sleepycat' },
      { title: 'SMLNJ', value: 'SMLNJ' },
      { title: 'SMPPL', value: 'SMPPL' },
      { title: 'SNIA', value: 'SNIA' },
      { title: 'Spencer-86', value: 'Spencer-86' },
      { title: 'Spencer-94', value: 'Spencer-94' },
      { title: 'Spencer-99', value: 'Spencer-99' },
      { title: 'SPL-1.0', value: 'SPL-1.0' },
      { title: 'SSH-OpenSSH', value: 'SSH-OpenSSH' },
      { title: 'SSH-short', value: 'SSH-short' },
      { title: 'SSPL-1.0', value: 'SSPL-1.0' },
      { title: 'SugarCRM-1.1.3', value: 'SugarCRM-1.1.3' },
      { title: 'SWL', value: 'SWL' },
      { title: 'TAPR-OHL-1.0', value: 'TAPR-OHL-1.0' },
      { title: 'TCL', value: 'TCL' },
      { title: 'TCP-wrappers', value: 'TCP-wrappers' },
      { title: 'TMate', value: 'TMate' },
      { title: 'TORQUE-1.1', value: 'TORQUE-1.1' },
      { title: 'TOSL', value: 'TOSL' },
      { title: 'TU-Berlin-1.0', value: 'TU-Berlin-1.0' },
      { title: 'TU-Berlin-2.0', value: 'TU-Berlin-2.0' },
      { title: 'UCL-1.0', value: 'UCL-1.0' },
      { title: 'Unicode-DFS-2015', value: 'Unicode-DFS-2015' },
      { title: 'Unicode-DFS-2016', value: 'Unicode-DFS-2016' },
      { title: 'Unicode-TOU', value: 'Unicode-TOU' },
      { title: 'Unlicense', value: 'Unlicense' },
      { title: 'UPL-1.0', value: 'UPL-1.0' },
      { title: 'Vim', value: 'Vim' },
      { title: 'VOSTROM', value: 'VOSTROM' },
      { title: 'VSL-1.0', value: 'VSL-1.0' },
      { title: 'W3C', value: 'W3C' },
      { title: 'W3C-19980720', value: 'W3C-19980720' },
      { title: 'W3C-20150513', value: 'W3C-20150513' },
      { title: 'Watcom-1.0', value: 'Watcom-1.0' },
      { title: 'Wsuipa', value: 'Wsuipa' },
      { title: 'WTFPL', value: 'WTFPL' },
      { title: 'X11', value: 'X11' },
      { title: 'Xerox', value: 'Xerox' },
      { title: 'XFree86-1.1', value: 'XFree86-1.1' },
      { title: 'xinetd', value: 'xinetd' },
      { title: 'Xnet', value: 'Xnet' },
      { title: 'xpp', value: 'xpp' },
      { title: 'XSkat', value: 'XSkat' },
      { title: 'YPL-1.0', value: 'YPL-1.0' },
      { title: 'YPL-1.1', value: 'YPL-1.1' },
      { title: 'Zed', value: 'Zed' },
      { title: 'Zend-2.0', value: 'Zend-2.0' },
      { title: 'Zimbra-1.3', value: 'Zimbra-1.3' },
      { title: 'Zimbra-1.4', value: 'Zimbra-1.4' },
      { title: 'Zlib', value: 'Zlib' },
      { title: 'zlib-acknowledgement', value: 'zlib-acknowledgement' },
      { title: 'ZPL-1.1', value: 'ZPL-1.1' },
      { title: 'ZPL-2.0', value: 'ZPL-2.0' },
      { title: 'ZPL-2.1', value: 'ZPL-2.1' },
    ],
  },
];
