//@ts-check
const prompts = require('prompts');
const validateNpmPackageName = require('validate-npm-package-name');
const { infoLog, warnLog } = require('./log');
const { exitCode } = require('./exitCodes');

/**
 * Prompt project configure dialog
 * @param {string} projectName
 * @returns {Promise<{ name: string, description: string, author: string, license: string }>}
 */
exports.propmtConfigureDialog = async (projectName = '') => {
  /**
   * Dialog inputs
   */
  const inputs = [
    {
      type: 'text',
      name: 'name',
      message: 'project name',
      initial: projectName,
      validate: (value) => {
        const ctx = validateNpmPackageName(value);
        if (ctx.validForNewPackages) {
          return true;
        } else {
          return (ctx.errors || []).concat(ctx.warnings || []).join(' and ');
        }
      },
    },
    {
      type: 'text',
      name: 'description',
      message: 'description',
      initial: (prev) => prev,
    },
    {
      type: 'text',
      name: 'author',
      message: 'author',
    },
    {
      type: 'autocomplete',
      name: 'license',
      message: 'license',
      initial: 'MIT',
      choices: [
        { title: '0BSD' },
        { title: 'AAL' },
        { title: 'Abstyles' },
        { title: 'Adobe-2006' },
        { title: 'Adobe-Glyph' },
        { title: 'ADSL' },
        { title: 'AFL-1.1' },
        { title: 'AFL-1.2' },
        { title: 'AFL-2.0' },
        { title: 'AFL-2.1' },
        { title: 'AFL-3.0' },
        { title: 'Afmparse' },
        { title: 'AGPL-1.0-only' },
        { title: 'AGPL-1.0-or-later' },
        { title: 'AGPL-3.0-only' },
        { title: 'AGPL-3.0-or-later' },
        { title: 'Aladdin' },
        { title: 'AMDPLPA' },
        { title: 'AML' },
        { title: 'AMPAS' },
        { title: 'ANTLR-PD' },
        { title: 'Apache-1.0' },
        { title: 'Apache-1.1' },
        { title: 'Apache-2.0' },
        { title: 'APAFML' },
        { title: 'APL-1.0' },
        { title: 'APSL-1.0' },
        { title: 'APSL-1.1' },
        { title: 'APSL-1.2' },
        { title: 'APSL-2.0' },
        { title: 'Artistic-1.0' },
        { title: 'Artistic-1.0-cl8' },
        { title: 'Artistic-1.0-Perl' },
        { title: 'Artistic-2.0' },
        { title: 'Bahyph' },
        { title: 'Barr' },
        { title: 'Beerware' },
        { title: 'BitTorrent-1.0' },
        { title: 'BitTorrent-1.1' },
        { title: 'blessing' },
        { title: 'BlueOak-1.0.0' },
        { title: 'Borceux' },
        { title: 'BSD-1-Clause' },
        { title: 'BSD-2-Clause' },
        { title: 'BSD-2-Clause-Patent' },
        { title: 'BSD-2-Clause-Views' },
        { title: 'BSD-3-Clause' },
        { title: 'BSD-3-Clause-Attribution' },
        { title: 'BSD-3-Clause-Clear' },
        { title: 'BSD-3-Clause-LBNL' },
        { title: 'BSD-3-Clause-No-Nuclear-License' },
        { title: 'BSD-3-Clause-No-Nuclear-License-2014' },
        { title: 'BSD-3-Clause-No-Nuclear-Warranty' },
        { title: 'BSD-3-Clause-Open-MPI' },
        { title: 'BSD-4-Clause' },
        { title: 'BSD-4-Clause-UC' },
        { title: 'BSD-Protection' },
        { title: 'BSD-Source-Code' },
        { title: 'BSL-1.0' },
        { title: 'bzip2-1.0.5' },
        { title: 'bzip2-1.0.6' },
        { title: 'CAL-1.0' },
        { title: 'CAL-1.0-Combined-Work-Exception' },
        { title: 'Caldera' },
        { title: 'CATOSL-1.1' },
        { title: 'CC-BY-1.0' },
        { title: 'CC-BY-2.0' },
        { title: 'CC-BY-2.5' },
        { title: 'CC-BY-3.0' },
        { title: 'CC-BY-3.0-AT' },
        { title: 'CC-BY-4.0' },
        { title: 'CC-BY-NC-1.0' },
        { title: 'CC-BY-NC-2.0' },
        { title: 'CC-BY-NC-2.5' },
        { title: 'CC-BY-NC-3.0' },
        { title: 'CC-BY-NC-4.0' },
        { title: 'CC-BY-NC-ND-1.0' },
        { title: 'CC-BY-NC-ND-2.0' },
        { title: 'CC-BY-NC-ND-2.5' },
        { title: 'CC-BY-NC-ND-3.0' },
        { title: 'CC-BY-NC-ND-3.0-IGO' },
        { title: 'CC-BY-NC-ND-4.0' },
        { title: 'CC-BY-NC-SA-1.0' },
        { title: 'CC-BY-NC-SA-2.0' },
        { title: 'CC-BY-NC-SA-2.5' },
        { title: 'CC-BY-NC-SA-3.0' },
        { title: 'CC-BY-NC-SA-4.0' },
        { title: 'CC-BY-ND-1.0' },
        { title: 'CC-BY-ND-2.0' },
        { title: 'CC-BY-ND-2.5' },
        { title: 'CC-BY-ND-3.0' },
        { title: 'CC-BY-ND-4.0' },
        { title: 'CC-BY-SA-1.0' },
        { title: 'CC-BY-SA-2.0' },
        { title: 'CC-BY-SA-2.5' },
        { title: 'CC-BY-SA-3.0' },
        { title: 'CC-BY-SA-3.0-AT' },
        { title: 'CC-BY-SA-4.0' },
        { title: 'CC-PDDC' },
        { title: 'CC0-1.0' },
        { title: 'CDDL-1.0' },
        { title: 'CDDL-1.1' },
        { title: 'CDLA-Permissive-1.0' },
        { title: 'CDLA-Sharing-1.0' },
        { title: 'CECILL-1.0' },
        { title: 'CECILL-1.1' },
        { title: 'CECILL-2.0' },
        { title: 'CECILL-2.1' },
        { title: 'CECILL-B' },
        { title: 'CECILL-C' },
        { title: 'CERN-OHL-1.1' },
        { title: 'CERN-OHL-1.2' },
        { title: 'CERN-OHL-P-2.0' },
        { title: 'CERN-OHL-S-2.0' },
        { title: 'CERN-OHL-W-2.0' },
        { title: 'ClArtistic' },
        { title: 'CNRI-Jython' },
        { title: 'CNRI-Python' },
        { title: 'CNRI-Python-GPL-Compatible' },
        { title: 'Condor-1.1' },
        { title: 'copyleft-next-0.3.0' },
        { title: 'copyleft-next-0.3.1' },
        { title: 'CPAL-1.0' },
        { title: 'CPL-1.0' },
        { title: 'CPOL-1.02' },
        { title: 'Crossword' },
        { title: 'CrystalStacker' },
        { title: 'CUA-OPL-1.0' },
        { title: 'Cube' },
        { title: 'curl' },
        { title: 'D-FSL-1.0' },
        { title: 'diffmark' },
        { title: 'DOC' },
        { title: 'Dotseqn' },
        { title: 'DSDP' },
        { title: 'dvipdfm' },
        { title: 'ECL-1.0' },
        { title: 'ECL-2.0' },
        { title: 'EFL-1.0' },
        { title: 'EFL-2.0' },
        { title: 'eGenix' },
        { title: 'Entessa' },
        { title: 'EPICS' },
        { title: 'EPL-1.0' },
        { title: 'EPL-2.0' },
        { title: 'ErlPL-1.1' },
        { title: 'etalab-2.0' },
        { title: 'EUDatagrid' },
        { title: 'EUPL-1.0' },
        { title: 'EUPL-1.1' },
        { title: 'EUPL-1.2' },
        { title: 'Eurosym' },
        { title: 'Fair' },
        { title: 'Frameworx-1.0' },
        { title: 'FreeImage' },
        { title: 'FSFAP' },
        { title: 'FSFUL' },
        { title: 'FSFULLR' },
        { title: 'FTL' },
        { title: 'GFDL-1.1-invariants-only' },
        { title: 'GFDL-1.1-invariants-or-later' },
        { title: 'GFDL-1.1-no-invariants-only' },
        { title: 'GFDL-1.1-no-invariants-or-later' },
        { title: 'GFDL-1.1-only' },
        { title: 'GFDL-1.1-or-later' },
        { title: 'GFDL-1.2-invariants-only' },
        { title: 'GFDL-1.2-invariants-or-later' },
        { title: 'GFDL-1.2-no-invariants-only' },
        { title: 'GFDL-1.2-no-invariants-or-later' },
        { title: 'GFDL-1.2-only' },
        { title: 'GFDL-1.2-or-later' },
        { title: 'GFDL-1.3-invariants-only' },
        { title: 'GFDL-1.3-invariants-or-later' },
        { title: 'GFDL-1.3-no-invariants-only' },
        { title: 'GFDL-1.3-no-invariants-or-later' },
        { title: 'GFDL-1.3-only' },
        { title: 'GFDL-1.3-or-later' },
        { title: 'Giftware' },
        { title: 'GL2PS' },
        { title: 'Glide' },
        { title: 'Glulxe' },
        { title: 'GLWTPL' },
        { title: 'gnuplot' },
        { title: 'GPL-1.0-only' },
        { title: 'GPL-1.0-or-later' },
        { title: 'GPL-2.0-only' },
        { title: 'GPL-2.0-or-later' },
        { title: 'GPL-3.0-only' },
        { title: 'GPL-3.0-or-later' },
        { title: 'gSOAP-1.3b' },
        { title: 'HaskellReport' },
        { title: 'Hippocratic-2.1' },
        { title: 'HPND' },
        { title: 'HPND-sell-variant' },
        { title: 'IBM-pibs' },
        { title: 'ICU' },
        { title: 'IJG' },
        { title: 'ImageMagick' },
        { title: 'iMatix' },
        { title: 'Imlib2' },
        { title: 'Info-ZIP' },
        { title: 'Intel' },
        { title: 'Intel-ACPI' },
        { title: 'Interbase-1.0' },
        { title: 'IPA' },
        { title: 'IPL-1.0' },
        { title: 'ISC' },
        { title: 'JasPer-2.0' },
        { title: 'JPNIC' },
        { title: 'JSON' },
        { title: 'LAL-1.2' },
        { title: 'LAL-1.3' },
        { title: 'Latex2e' },
        { title: 'Leptonica' },
        { title: 'LGPL-2.0-only' },
        { title: 'LGPL-2.0-or-later' },
        { title: 'LGPL-2.1-only' },
        { title: 'LGPL-2.1-or-later' },
        { title: 'LGPL-3.0-only' },
        { title: 'LGPL-3.0-or-later' },
        { title: 'LGPLLR' },
        { title: 'Libpng' },
        { title: 'libpng-2.0' },
        { title: 'libselinux-1.0' },
        { title: 'libtiff' },
        { title: 'LiLiQ-P-1.1' },
        { title: 'LiLiQ-R-1.1' },
        { title: 'LiLiQ-Rplus-1.1' },
        { title: 'Linux-OpenIB' },
        { title: 'LPL-1.0' },
        { title: 'LPL-1.02' },
        { title: 'LPPL-1.0' },
        { title: 'LPPL-1.1' },
        { title: 'LPPL-1.2' },
        { title: 'LPPL-1.3a' },
        { title: 'LPPL-1.3c' },
        { title: 'MakeIndex' },
        { title: 'MirOS' },
        { title: 'MIT' },
        { title: 'MIT-0' },
        { title: 'MIT-advertising' },
        { title: 'MIT-CMU' },
        { title: 'MIT-enna' },
        { title: 'MIT-feh' },
        { title: 'MITNFA' },
        { title: 'Motosoto' },
        { title: 'mpich2' },
        { title: 'MPL-1.0' },
        { title: 'MPL-1.1' },
        { title: 'MPL-2.0' },
        { title: 'MPL-2.0-no-copyleft-exception' },
        { title: 'MS-PL' },
        { title: 'MS-RL' },
        { title: 'MTLL' },
        { title: 'MulanPSL-1.0' },
        { title: 'MulanPSL-2.0' },
        { title: 'Multics' },
        { title: 'Mup' },
        { title: 'NASA-1.3' },
        { title: 'Naumen' },
        { title: 'NBPL-1.0' },
        { title: 'NCGL-UK-2.0' },
        { title: 'NCSA' },
        { title: 'Net-SNMP' },
        { title: 'NetCDF' },
        { title: 'Newsletr' },
        { title: 'NGPL' },
        { title: 'NIST-PD' },
        { title: 'NIST-PD-fallback' },
        { title: 'NLOD-1.0' },
        { title: 'NLPL' },
        { title: 'Nokia' },
        { title: 'NOSL' },
        { title: 'Noweb' },
        { title: 'NPL-1.0' },
        { title: 'NPL-1.1' },
        { title: 'NPOSL-3.0' },
        { title: 'NRL' },
        { title: 'NTP' },
        { title: 'NTP-0' },
        { title: 'O-UDA-1.0' },
        { title: 'OCCT-PL' },
        { title: 'OCLC-2.0' },
        { title: 'ODbL-1.0' },
        { title: 'ODC-By-1.0' },
        { title: 'OFL-1.0' },
        { title: 'OFL-1.0-no-RFN' },
        { title: 'OFL-1.0-RFN' },
        { title: 'OFL-1.1' },
        { title: 'OFL-1.1-no-RFN' },
        { title: 'OFL-1.1-RFN' },
        { title: 'OGC-1.0' },
        { title: 'OGL-Canada-2.0' },
        { title: 'OGL-UK-1.0' },
        { title: 'OGL-UK-2.0' },
        { title: 'OGL-UK-3.0' },
        { title: 'OGTSL' },
        { title: 'OLDAP-1.1' },
        { title: 'OLDAP-1.2' },
        { title: 'OLDAP-1.3' },
        { title: 'OLDAP-1.4' },
        { title: 'OLDAP-2.0' },
        { title: 'OLDAP-2.0.1' },
        { title: 'OLDAP-2.1' },
        { title: 'OLDAP-2.2' },
        { title: 'OLDAP-2.2.1' },
        { title: 'OLDAP-2.2.2' },
        { title: 'OLDAP-2.3' },
        { title: 'OLDAP-2.4' },
        { title: 'OLDAP-2.5' },
        { title: 'OLDAP-2.6' },
        { title: 'OLDAP-2.7' },
        { title: 'OLDAP-2.8' },
        { title: 'OML' },
        { title: 'OpenSSL' },
        { title: 'OPL-1.0' },
        { title: 'OSET-PL-2.1' },
        { title: 'OSL-1.0' },
        { title: 'OSL-1.1' },
        { title: 'OSL-2.0' },
        { title: 'OSL-2.1' },
        { title: 'OSL-3.0' },
        { title: 'Parity-6.0.0' },
        { title: 'Parity-7.0.0' },
        { title: 'PDDL-1.0' },
        { title: 'PHP-3.0' },
        { title: 'PHP-3.01' },
        { title: 'Plexus' },
        { title: 'PolyForm-Noncommercial-1.0.0' },
        { title: 'PolyForm-Small-Business-1.0.0' },
        { title: 'PostgreSQL' },
        { title: 'PSF-2.0' },
        { title: 'psfrag' },
        { title: 'psutils' },
        { title: 'Python-2.0' },
        { title: 'Qhull' },
        { title: 'QPL-1.0' },
        { title: 'Rdisc' },
        { title: 'RHeCos-1.1' },
        { title: 'RPL-1.1' },
        { title: 'RPL-1.5' },
        { title: 'RPSL-1.0' },
        { title: 'RSA-MD' },
        { title: 'RSCPL' },
        { title: 'Ruby' },
        { title: 'SAX-PD' },
        { title: 'Saxpath' },
        { title: 'SCEA' },
        { title: 'Sendmail' },
        { title: 'Sendmail-8.23' },
        { title: 'SGI-B-1.0' },
        { title: 'SGI-B-1.1' },
        { title: 'SGI-B-2.0' },
        { title: 'SHL-0.5' },
        { title: 'SHL-0.51' },
        { title: 'SimPL-2.0' },
        { title: 'SISSL' },
        { title: 'SISSL-1.2' },
        { title: 'Sleepycat' },
        { title: 'SMLNJ' },
        { title: 'SMPPL' },
        { title: 'SNIA' },
        { title: 'Spencer-86' },
        { title: 'Spencer-94' },
        { title: 'Spencer-99' },
        { title: 'SPL-1.0' },
        { title: 'SSH-OpenSSH' },
        { title: 'SSH-short' },
        { title: 'SSPL-1.0' },
        { title: 'SugarCRM-1.1.3' },
        { title: 'SWL' },
        { title: 'TAPR-OHL-1.0' },
        { title: 'TCL' },
        { title: 'TCP-wrappers' },
        { title: 'TMate' },
        { title: 'TORQUE-1.1' },
        { title: 'TOSL' },
        { title: 'TU-Berlin-1.0' },
        { title: 'TU-Berlin-2.0' },
        { title: 'UCL-1.0' },
        { title: 'Unicode-DFS-2015' },
        { title: 'Unicode-DFS-2016' },
        { title: 'Unicode-TOU' },
        { title: 'Unlicense' },
        { title: 'UPL-1.0' },
        { title: 'Vim' },
        { title: 'VOSTROM' },
        { title: 'VSL-1.0' },
        { title: 'W3C' },
        { title: 'W3C-19980720' },
        { title: 'W3C-20150513' },
        { title: 'Watcom-1.0' },
        { title: 'Wsuipa' },
        { title: 'WTFPL' },
        { title: 'X11' },
        { title: 'Xerox' },
        { title: 'XFree86-1.1' },
        { title: 'xinetd' },
        { title: 'Xnet' },
        { title: 'xpp' },
        { title: 'XSkat' },
        { title: 'YPL-1.0' },
        { title: 'YPL-1.1' },
        { title: 'Zed' },
        { title: 'Zend-2.0' },
        { title: 'Zimbra-1.3' },
        { title: 'Zimbra-1.4' },
        { title: 'Zlib' },
        { title: 'zlib-acknowledgement' },
        { title: 'ZPL-1.1' },
        { title: 'ZPL-2.0' },
        { title: 'ZPL-2.1' },
      ],
    },
  ];

  /**
   * Cancel prompt
   */
  const onWizardCancel = () => {
    warnLog(exitCode.cancelledCreatePj.subject);
    infoLog(exitCode.cancelledCreatePj.message);
    process.exit(exitCode.cancelledCreatePj.code);
  };

  // @ts-ignore
  return await prompts(inputs, { onCancel: onWizardCancel });
};
