name: testing on PR to main
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
jobs:
  validate-npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
      - name: can npm publish?
        run: pnpx can-npm-publish
  basics-testing-on-ubuntu:
    needs:
      - validate-npm-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'
      - name: pnpm continuous install
        run: pnpm install
      - name: git configure
        run: |
          git config --global user.email test@example.com
          git config --global user.name test
      - name: run testing
        run: pnpm headless-test
